projectx/urls.py
import allauth
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views
from twift.forms import LoginForm

admin.autodiscover()

urlpatterns = [
    url(r'^$', include('twift.urls')),
    url(r'^twift/', include('twift.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/', TemplateView.as_view(template_name='account/profile.html')),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

twift/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import TemplateView

# We are adding a URL called /home
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/', views.home, name='home'),
    url(r'^thanks/', TemplateView.as_view(template_name='twift/thanks.html'),
        name='thanks'),
    url(r'^show_available_rides', views.show_available_rides,
        name='show_available_rides'),
    url(r'^availRide', views.avail_ride, name='avail_ride'),
    url(r'^offerNewRide/', views.offer_ride, name='offer_ride'),
    url(r'^getDriverDetails/', views.driver_details, name='driver_details'),
    url(r'^getCustomers/', views.get_customers, name='get_customers'),
]

twift/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from datetime import datetime

from . import constants


class UserDetails(models.Model):
    """User Details."""

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    address = JSONField(default=list([]))
    isdriver = models.BooleanField()
    gender = models.CharField(
        max_length=1, choices=constants.GENDER_CHOICES, default=constants.MALE)


class DriverUsers(models.Model):
    """Driver details model."""

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    driverlicense = models.CharField(max_length=20)

    def __str__(self):
        """Return driving license."""
        return self.driverlicense


class VehicleDetails(models.Model):
    """Vehicle details model."""

    vehicleregistration = models.CharField(max_length=20)
    vehiclemodel = models.CharField(max_length=20)
    milage = models.FloatField()
    owner = models.ForeignKey(User)

    def __str__(self):
        """Return vehicleregistration."""
        return self.vehicleregistration


class Journey(models.Model):
    """Journey model upon confirmation."""

    passenger = models.ForeignKey(User, related_name='the_passsenger')
    driver = models.ForeignKey(User, related_name='the_driver')
    lat_src = models.FloatField()
    lng_src = models.FloatField()
    lat_dest = models.FloatField()
    lng_dest = models.FloatField()
    waypoints = JSONField(default=list([]))


class JourneyFeedback(models.Model):
    """Journey feedback model."""

    uid = models.ForeignKey(User)
    journeyid = models.ForeignKey(Journey)
    feedback = models.CharField(max_length=100)


class OfferRides(models.Model):
    """Offering rides model."""

    user = models.ForeignKey(DriverUsers)
    source = models.CharField(max_length=255)
    destination = models.CharField(max_length=255)
    lat_src = models.FloatField()
    lng_src = models.FloatField()
    lat_dest = models.FloatField()
    lng_dest = models.FloatField()
    seats = models.IntegerField()
    date_published = models.DateTimeField(auto_now_add=True, auto_now=False)


class AvailRideModel(models.Model):
    """Available rides."""

    uid = models.ForeignKey(User)
    source = models.CharField(max_length=255)
    destination = models.CharField(max_length=255)
    lat_src = models.FloatField()
    lng_src = models.FloatField()
    lat_dest = models.FloatField()
    lng_dest = models.FloatField()
    date_published = models.DateTimeField(default=datetime.now, blank=True)


class AvailToOffer(models.Model):
    """Ride request model."""

    avail = models.ForeignKey(AvailRideModel)
    offer = models.ForeignKey(OfferRides)

twift/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms

from .models import AvailRideModel, OfferRides, DriverUsers
from django.utils import html


class SubmitButtonWidget(forms.Widget):
    """Submit button widget."""

    def render(self, name, value, attrs=None):
        """Render page."""
        return '<input type="submit" name="%s" value="%s">' % (
            html.escape(name), html.escape(value))


class SubmitButtonField(forms.Field):
    """Submit button field."""

    def __init__(self, *args, **kwargs):
        """Initialise."""
        if not kwargs:
            kwargs = {}
        kwargs["widget"] = SubmitButtonWidget

        super(SubmitButtonField, self).__init__(*args, **kwargs)

    def clean(self, value):
        """Clean."""
        return value


# If you don't do this you cannot use Bootstrap CSS
class LoginForm(AuthenticationForm):
    """Login form."""

    username = forms.CharField(
        label="Username",
        max_length=30,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(
        label="Password",
        max_length=30,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'name': 'password'}))


class AvailRide(forms.Form):
    """Availride form."""

    source = forms.CharField(
        widget=forms.HiddenInput(
            attrs={'class': 'form-control', 'name': 'source'}))
    destination = forms.CharField(
        widget=forms.HiddenInput(
            attrs={'class': 'form-control', 'name': 'destination'}))
    lat_src = forms.CharField(
        widget=forms.HiddenInput(
            attrs={'class': 'form-control', 'name': 'lat_src'}))
    lng_src = forms.CharField(
        widget=forms.HiddenInput(
            attrs={'class': 'form-control', 'name': 'lng_src'}))
    lat_dest = forms.CharField(
        widget=forms.HiddenInput(
            attrs={'class': 'form-control', 'name': 'lat_dest'}))
    lng_dest = forms.CharField(
        widget=forms.HiddenInput(
            attrs={'class': 'form-control', 'name': 'lng_dest'}))
    duration = forms.CharField(
        widget=forms.HiddenInput(
            attrs={'class': 'form-control', 'name': 'duration', 'value': '0'}))

    class Meta:
        """Mata data."""

        model = AvailRideModel


class ChooseRides(forms.Form):
    """Choose ride form."""

    rideschoices = forms.CharField(
        widget=forms.HiddenInput(
            attrs={
                'class': 'form-control',
                'name': 'rideschoices', 'value': '[]'}))
    searchField = forms.CharField(
        widget=forms.HiddenInput(
            attrs={'class': 'form-control', 'name': 'searchField'}))
    submit_button = SubmitButtonField(
        label="Choose Rides",
        initial=u"Choose Rides", disabled='true')


class OfferRideForm(forms.Form):
    """Offer ride form."""

    CHOICES = (('1', '1',), ('2', '2',))
    source = forms.CharField(
        label="Source",
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    destination = forms.CharField(
        label="Destination",
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    seats = forms.ChoiceField(
        label="Seats Available", choices=CHOICES,
        widget=forms.Select(attrs={'class': 'form-control selector'}))
    lat_src = forms.FloatField(required=False, widget=forms.HiddenInput())
    lng_src = forms.FloatField(required=False, widget=forms.HiddenInput())
    lat_dest = forms.FloatField(required=False, widget=forms.HiddenInput())
    lng_dest = forms.FloatField(required=False, widget=forms.HiddenInput())

    class Meta:
        """Meta data."""

        model = OfferRides
        fields = ('source',)


class DriverDetailsForm(forms.ModelForm):
    """Driver details form."""

    driverlicense = forms.CharField(
        label="Driver License",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        """Meta data."""

        model = DriverUsers
        fields = ('driverlicense',)

twift/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from .forms import AvailRide, OfferRideForm, ChooseRides, DriverDetailsForm
from .models import AvailRideModel, OfferRides, DriverUsers, AvailToOffer
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
import logging
import json

from django.core.serializers.json import DjangoJSONEncoder

from django.core import serializers
log = logging.getLogger(__name__)


def home(request):
    """Home page."""
    return render(request, "home.html")


def thanks(request):
    """Thank page."""
    if request.method == 'POST':
        return render(request, "twift/offerNewRide.html")


def get_customers(request):
    """Get customers who wants ride."""
    source = None
    destination = None
    customers = None
    if request.method == 'GET':
        source = request.GET['source']
        print(source)
        destination = request.GET['destination']
        print(destination)
        if source and destination:
            print("hello")
            customers = (AvailRideModel.objects.select_related().filter(
                source=unicode(source),
                destination=unicode(destination)).order_by(
                    '-date_published').values(
                        'uid', 'source', 'destination', 'date_published',
                        'uid__first_name', 'uid__last_name'))
            print('Inside get customers')
            print(customers)
        else:
            customers = (AvailRideModel.objects.select_related().values(
                'uid', 'source', 'destination', 'date_published',
                'uid__first_name', 'uid__last_name'))
            print('Inside get customers')
            print(customers)
        try:
            json_customers = json.dumps(list(customers), cls=DjangoJSONEncoder)
        except Exception as e:
            print('Inside exception')
            print(str(e))
        print(json_customers)
    return HttpResponse(json_customers)


def driver_details(request):
    """Get users driver related information and redirect to offer ride page."""
    if request.method == 'POST':
        form = DriverDetailsForm(request.POST)
        if form.is_valid():
            user_id = request.user.pk
            data = form.cleaned_data
            data['user_id'] = user_id
            try:
                DriverUsers.objects.create(**data)
                return HttpResponseRedirect(reverse('offer_ride'))
            except Exception as e:
                print(str(e))
                return HttpResponseRedirect(reverse('offer_ride'))
    else:
        form = DriverDetailsForm()
    return render(request, "twift/getDriverDetails.html", {'form': form})


def offer_ride(request):
    """Offer ride page."""
    if request.method == 'POST':
        form = OfferRideForm(request.POST)
        if form.is_valid():
            du = DriverUsers.objects.filter(user=request.user)
            print(du[0].user_id)
            data = form.cleaned_data
            print(data)
            data['user'] = du[0]

            try:
                OfferRides.objects.create(**data)
                return render_to_response('home.html')
            except Exception as e:
                print(data)
                print(str(e))
                return HttpResponseRedirect(reverse('home'))
    else:
        # See if driver registered
        driver_exists = DriverUsers.objects.filter(
            user_id=request.user.pk).exists()
        if not driver_exists:
            # Set driver details
            form = DriverDetailsForm()
            return HttpResponseRedirect("../getDriverDetails")
        else:
            form = OfferRideForm()
            return render(request, "twift/offerNewRide.html", {'form': form})


@login_required
def avail_ride(request):
    """Set customers information who wants ride."""
    if request.method == 'POST':
        form = AvailRide(request.POST)
        if form.is_valid():

            try:
                dur = form.cleaned_data["duration"]
                log.info(dur)
                datenew = datetime.now() + timedelta(minutes=int(dur))
                log.info(datenew)
                log.info(datetime.now())
                newridereq = AvailRideModel(
                    uid=request.user,
                    source=form.cleaned_data["source"],
                    lat_src=form.cleaned_data["lat_src"],
                    lng_src=form.cleaned_data["lng_src"],
                    destination=form.cleaned_data["destination"],
                    lat_dest=form.cleaned_data["lat_dest"],
                    lng_dest=form.cleaned_data["lng_dest"],
                    date_published=datenew)
                log.info(form.cleaned_data)
                serialized_obj = serializers.serialize('json', [newridereq, ])
                # newridereq.save()
                log.info(newridereq.date_published)
                ride_offers = OfferRides.objects.select_related()
                print(ride_offers)
                form1 = ChooseRides(
                    {
                        'searchField': serialized_obj,
                        'rideschoices': '[]',
                        'submit_button': 'Choose Rides and Submit'})
                return render(
                    request,
                    'twift/avaiRide.html',
                    {
                        'form': form,
                        'ride_offers': ride_offers,
                        'form1': form1})
            except Exception as e:
                log.error(newridereq)
                log.error(e)
                return HttpResponseRedirect(reverse('home'))

    else:
        form = AvailRide()

    return render(request, 'twift/avaiRide.html', {'form': form})


def show_available_rides(request):
    """Show available rides."""
    if request.method == 'POST':
        form = ChooseRides(request.POST)
        if form.is_valid():
            log.info(form.cleaned_data)
            rideavailed = json.loads(form.cleaned_data["rideschoices"])
            searchField = json.loads(form.cleaned_data["searchField"])
            newridereq = AvailRideModel(
                uid=request.user,
                source=searchField[0]['fields']['source'],
                lat_src=searchField[0]['fields']["lat_src"],
                lng_src=searchField[0]['fields']["lng_src"],
                destination=searchField[0]['fields']["destination"],
                lat_dest=searchField[0]['fields']["lat_dest"],
                lng_dest=searchField[0]['fields']["lng_dest"],
                date_published=searchField[0]['fields']['date_published'])
            newridereq.save()
            for value in rideavailed:
                log.info(value)
                avail = newridereq
                offer = OfferRides.objects.filter(
                    id=int(value['driver_ride_id']))[0]
                newatoo = AvailToOffer(avail=avail, offer=offer)
                newatoo.save()

            return render(request, "home.html")
    ride_offers = OfferRides.objects.all()
    print(ride_offers.count())
    return render(
        request, 'twift/rideOffers.html',
        {'ride_offers': ride_offers})

templates/twift/avaiRide.html
{% extends "base.html" %}
{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
{% load staticfiles %}
<style>
    html, body{
        height: 100%;
    }
    .rowspace {
        margin-bottom: 20px;
    }
</style>

<div class="container">
    <div class="row" style="background:lightseagreen">
        <h2 class="text-center">Twift! Two wheeler lift</h2>
        <h4 class="text-center">Ride Share!!</h4><br/><br/><br/>
        <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places&key=AIzaSyDNDQMWfiSliKDmlNRokulCXBLKZBebBnQ"></script>
     

        <div class="container" style="background: white">
        <h1 class="header center black-text">Find a Ride</h1>
        <form method="post"    class="form-horizontal">
            {% csrf_token %}
            {{ form}}

<div class="row">
                <div class="form-group">
                    <div class="text-center col-md-2 col-md-offset-4 rowspace">
              <a class='dropdown-button btn' id="dd2" href='#' data-activates='dropdown2'>Travel Now</a>

  <!-- Dropdown Structure -->
  <ul id='dropdown2' class='dropdown-content'>
    <li><a href="#!" onclick="document.getElementById('dd2').text='Travel Now';document.getElementById('id_duration').value='0';">Travel Now</a></li>
    <li><a href="#!" onclick="document.getElementById('dd2').text='In 30 minutes';document.getElementById('id_duration').value='30';">In 30 minutes</a></li>
    
    <li ><a href="#!" onclick="document.getElementById('dd2').text='In 1 hr';;document.getElementById('id_duration').value='60';">In 1 hr</a></li>
  </ul>
  </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="text-center col-md-2 col-md-offset-4 rowspace">
                        <input type="text" id="srcPlaces" style="width: 250px" placeholder="Source" required="required" value="{% if form.source.value != None  %} {{form.source.value}} {% endif %}"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="text-center col-md-4 col-md-offset-4 rowspace">
                        <input type="text" id="destPlaces" style="width: 250px" placeholder="Destination" required="required" value="{% if form.destination.value != None  %} {{form.destination.value}} {% endif %}" />
                    </div>
                </div>
            </div>
            <div class="text-center col-md-4 col-md-offset-4 rowspace">
                <button class="btn waves-effect waves-light" type="submit"> Search  <i class="material-icons right">search</i></button>
            </div>
        </form>
         <div class="row">
         <span style="cursor:pointer">
         {% for ride in ride_offers %}
      <div class="row">
        <div class="col s12 m12">
<ul class="collection" >
    <li class="collection-item avatar">
    {% for account in ride.user.user.socialaccount_set.all %}
      <img src="{{ account.get_avatar_url }}" alt="" class="circle">
      {% endfor %}
              <span class="title">{{ ride.user.user.first_name   }} </span>
              <p>Source: {{ ride.source }}</p>
              <br/>
        <p>Destination:{{ ride.destination }}</p>     <a href="#!" class="secondary-content" onclick="ridechosen({{ride.id}},this)"><i class="material-icons" >add</i></a>
    </li></ul>
    </div></div>
     

   
             
{% endfor %}</span>
 <form method="post" action="/twift/show_available_rides/" class="form-horizontal">
            {% csrf_token %}
            {{ form1}}
  </form>

<script   src="https://code.jquery.com/jquery-3.1.0.js"   integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk="   crossorigin="anonymous"></script>  
 
{% block customjs %}

<script src = "{% static 'js/availRide.js' %}">
  

</script>

{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

templates/twift/getDriverDetails.html
{% extends "base.html" %}
{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
<style>
    #mainContainer {
        width: 100% !important;
    }
</style>

<div class="container" id="mainContainer" style="background:lightseagreen">
    <div class="row" style="background:lightseagreen">
        <h2 class="text-center">Twift! Two wheeler lift</h2>
        <h4 class="text-center">Ride Share!!</h4><br/><br/><br/>

        <div class="container" style="background: white">
            <form action="" method="post">
                {% csrf_token %}
                {{ form }}
                <br />
                <input type="submit" value="Add Details" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script_content %}
{% endblock %}

templates/twift/offerNewRide.html
{% extends "base.html" %}
{% load i18n %}
{% load account socialaccount %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
<style>
    #mainContainer {
        width: 100% !important;
    }
</style>

<div class="container" id="mainContainer">
    <div class="row">
        <h2 class="text-center">Twift! Two wheeler lift</h2>
        <h4 class="text-center">Ride Share!!</h4><br/><br/><br/>
        <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places&key=AIzaSyDNDQMWfiSliKDmlNRokulCXBLKZBebBnQ"></script>

        <script>
            function calculateRoute(from, to) {
                // Center initialized to Naples, Italy
                var myOptions = {
                    zoom: 10,
                    center: new google.maps.LatLng(40.84, 14.25),
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                // Draw the map
                var mapObject = new google.maps.Map(document.getElementById("map"), myOptions);

                var directionsService = new google.maps.DirectionsService();
                var directionsRequest = {
                    origin: from,
                    destination: to,
                    travelMode: google.maps.DirectionsTravelMode.DRIVING,
                    unitSystem: google.maps.UnitSystem.METRIC
                };
                directionsService.route(
                    directionsRequest,
                    function(response, status)
                    {
                        if (status == google.maps.DirectionsStatus.OK)
                        {
                            new google.maps.DirectionsRenderer({
                                map: mapObject,
                                directions: response
                            });
                        }
                    else
                        $("#error").append("Unable to retrieve your route<br />");
                  }
                );
              }
        </script>

        <script type="text/javascript">
            google.maps.event.addDomListener(window, 'load', function () {
                var srcplaces = new google.maps.places.Autocomplete(document.getElementById('id_source'));
                google.maps.event.addListener(srcplaces, 'place_changed', function () {
                    var place = srcplaces.getPlace();
                    var address = place.formatted_address;
                    var latitude = place.geometry.location.lat();
                    var longitude = place.geometry.location.lng();
                    var mesg = "Address: " + address;
                    mesg += "\nLatitude: " + latitude;
                    mesg += "\nLongitude: " + longitude;
                    $('#id_lat_src').val(latitude);
                    $('#id_lng_src').val(longitude);
                });

                var destplaces = new google.maps.places.Autocomplete(document.getElementById('id_destination'));
                google.maps.event.addListener(destplaces, 'place_changed', function () {
                    var place = destplaces.getPlace();
                    var address = place.formatted_address;
                    var latitude = place.geometry.location.lat();
                    var longitude = place.geometry.location.lng();
                    var mesg = "Address: " + address;
                    mesg += "\nLatitude: " + latitude;
                    mesg += "\nLongitude: " + longitude;
                    $('#id_lat_dest').val(latitude);
                    $('#id_lng_dest').val(longitude);
                });
            });
        </script>

        <style type="text/css">
            #map {
                width: 600px;
                height: 400px;
                margin-top: 10px;
            }
        </style>

        <!-- Left Panel -->
        <div class="col-xs-6">
            <div class="container" style="background: white">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <br />
                    <input type="button" value="Route" id="route" />
                    <input type="submit" value="Publish" />
                    <input type="button" value="Show Finders" id="customers"/>
                </form>
                <div id="map"></div>
            </div>
        </div>

        <!-- Right Panel -->
        <div class="col-xs-6">
            <div class="container">
                <div class="row">
                    <table class="bordered highlight lime lighten-3"id="location">
                        <thead>
                            <th>Name</th>
                             <th>Source</th>
                             <th>Destination</th>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block script_content %}
    <script>
        $(document).ready(function() {
            // If the browser supports the Geolocation API
            if (typeof navigator.geolocation == "undefined") {
                $("#error").text("Your browser doesn't support the Geolocation API");
                return;
            }

            $('#route').click(function(){
                event.preventDefault();
                calculateRoute($("#id_source").val(), $("#id_destination").val());
            });

            $('#customers').click(function() {
                event.preventDefault();
                var src = $("#id_source").val();
                var dest = $("#id_destination").val();
                calculateRoute(src, dest);

                $.get('/twift/getCustomers/', {source: src, destination: dest}, function(data){
                    output = "";
                    var jsonData = $.parseJSON(data);

                    $('#location tbody').empty(); 
                    for(var i=0; i<jsonData.length; i++) {
                        $("#location tbody").append(
                            "<tr>"
                                +"<td>"+jsonData[i].uid__first_name+" "+
                                    jsonData[i].uid__last_name+"</td>"
                                +"<td>"+jsonData[i].source+"</td>"
                                +"<td>"+jsonData[i].destination+"</td>"
                            +"</tr>" );
                    }
                });
            })
        });
    </script>
{% endblock %}

templates/twift/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Twift</title>
</head>
<body>
Thanks for the ride offer.
</body>
</html>